// <auto-generated />
using Dimension_Data_MVC_CORE_Project2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dimension_Data_MVC_CORE_Project2.Data.Migrations
{
    [DbContext(typeof(HumanResourceContext))]
    [Migration("20201103021522_InitialHumanResourceContextMigration")]
    partial class InitialHumanResourceContextMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dimension_Data_MVC_CORE_Project2.Models.HumanResource", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Age")
                        .HasColumnType("real");

                    b.Property<string>("BusinessTravel")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<float>("DistanceFromHome")
                        .HasColumnType("real");

                    b.Property<string>("EducationField")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<float>("EmployeeNumber")
                        .HasColumnType("real");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<float>("NumCompaniesWorked")
                        .HasColumnType("real");

                    b.Property<string>("OverTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<float>("TotalWorkingYears")
                        .HasColumnType("real");

                    b.Property<float>("TrainingTimesLastYear")
                        .HasColumnType("real");

                    b.Property<float>("YearsAtCompany")
                        .HasColumnType("real");

                    b.Property<float>("YearsInCurrentRole")
                        .HasColumnType("real");

                    b.Property<float>("YearsSinceLastPromotion")
                        .HasColumnType("real");

                    b.Property<float>("YearsWithCurrManager")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("HumanResources");
                });
#pragma warning restore 612, 618
        }
    }
}
